import { createContext, useState } from "react";
export const EmployeeContext = createContext();

export const EmployeeProvider = ({ children }) => {
  const [list, setList] = useState(fakeData);

  const addEmployee = (employee) => {
    setList([...list, employee]);
  };
  return (
    <EmployeeContext.Provider value={{ list, setList, addEmployee }}>
      {children}
    </EmployeeContext.Provider>
  );
};

const fakeData = [
  [
    {
      firstName: "Cohen",
      name: "Farrell",
      startDate: "11-28-2017",
      department: "Marketing",
      dateOfBirth: "01-02-1973",
      street: "645 Virginia Place",
      city: "Cawood",
      state: "Rhode Island",
      zipCode: 11510,
    },
    {
      firstName: "Miller",
      name: "Key",
      startDate: "01-12-2022",
      department: "Marketing",
      dateOfBirth: "04-06-1974",
      street: "885 Farragut Road",
      city: "Torboy",
      state: "Arizona",
      zipCode: 20743,
    },
    {
      firstName: "Clarice",
      name: "Gallegos",
      startDate: "08-18-2015",
      department: "Marketing",
      dateOfBirth: "06-17-1986",
      street: "373 Bliss Terrace",
      city: "Troy",
      state: "North Dakota",
      zipCode: 31146,
    },
    {
      firstName: "Bernard",
      name: "Johns",
      startDate: "05-30-2019",
      department: "Marketing",
      dateOfBirth: "11-19-1978",
      street: "550 Middleton Street",
      city: "Dowling",
      state: "Puerto Rico",
      zipCode: 35553,
    },
    {
      firstName: "Rush",
      name: "Sykes",
      startDate: "01-22-2022",
      department: "Marketing",
      dateOfBirth: "09-05-1984",
      street: "967 Huron Street",
      city: "Eagletown",
      state: "Wisconsin",
      zipCode: 73090,
    },
    {
      firstName: "Hubbard",
      name: "Hoffman",
      startDate: "03-12-2014",
      department: "Marketing",
      dateOfBirth: "02-25-1970",
      street: "833 Vernon Avenue",
      city: "Bawcomville",
      state: "Missouri",
      zipCode: 84499,
    },
    {
      firstName: "Andrea",
      name: "Green",
      startDate: "07-09-2014",
      department: "Marketing",
      dateOfBirth: "05-27-1974",
      street: "202 Stockton Street",
      city: "Moscow",
      state: "Alabama",
      zipCode: 65212,
    },
    {
      firstName: "Liza",
      name: "Vaughan",
      startDate: "06-07-2016",
      department: "Marketing",
      dateOfBirth: "03-15-1975",
      street: "944 Bergen Place",
      city: "Vandiver",
      state: "Kansas",
      zipCode: 67793,
    },
    {
      firstName: "Laverne",
      name: "Bond",
      startDate: "05-23-2017",
      department: "Marketing",
      dateOfBirth: "07-10-1982",
      street: "511 Varanda Place",
      city: "Greensburg",
      state: "Ohio",
      zipCode: 60131,
    },
    {
      firstName: "Noel",
      name: "Lara",
      startDate: "10-21-2019",
      department: "Marketing",
      dateOfBirth: "03-03-1979",
      street: "317 Nelson Street",
      city: "Dodge",
      state: "Louisiana",
      zipCode: 11475,
    },
    {
      firstName: "Bush",
      name: "Cline",
      startDate: "01-02-2012",
      department: "Marketing",
      dateOfBirth: "07-15-1974",
      street: "219 Christopher Avenue",
      city: "Bannock",
      state: "Montana",
      zipCode: 90361,
    },
    {
      firstName: "Susanna",
      name: "Cohen",
      startDate: "09-21-2022",
      department: "Marketing",
      dateOfBirth: "09-26-1985",
      street: "964 Chester Court",
      city: "Machias",
      state: "Marshall Islands",
      zipCode: 63173,
    },
    {
      firstName: "Bell",
      name: "Andrews",
      startDate: "05-30-2021",
      department: "Marketing",
      dateOfBirth: "05-30-1982",
      street: "652 Cox Place",
      city: "Whitmer",
      state: "Nevada",
      zipCode: 95262,
    },
    {
      firstName: "Lily",
      name: "Waters",
      startDate: "05-22-2014",
      department: "Marketing",
      dateOfBirth: "02-14-1974",
      street: "899 Amity Street",
      city: "Lawrence",
      state: "South Dakota",
      zipCode: 25534,
    },
  ],
];
